[package]
name = "three"
version = "0.1.0"
authors = ["Jiangbin Zhao <zhaojiangbin@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.3.1"

[[bench]]
name = "write"
harness = false
